services:
  db:
    image: postgres:17-alpine
    container_name: bank-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=bankdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    #volumes:
    #  - postgres-data:/var/lib/postgresql/data
    #networks:
    #  - bank-network

#networks:
#  bank-network:
#    driver: bridge

#volumes:
#  postgres-data: